version: '3.8'
services:
  llm-quality-service:
    build: .
    platform: linux/amd64  # 确保兼容性
    ports:
      - "50051:50051"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONPATH=/app
    command: ["python", "backend/app.py"]