# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import llm_quality_pb2 as llm__quality__pb2


class LLMQualityServiceStub(object):
    """gRPC 服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
                '/llm_quality.LLMQualityService/Generate',
                request_serializer=llm__quality__pb2.GenerateRequest.SerializeToString,
                response_deserializer=llm__quality__pb2.GenerateResponse.FromString,
                )
        self.AutoCorrect = channel.unary_unary(
                '/llm_quality.LLMQualityService/AutoCorrect',
                request_serializer=llm__quality__pb2.CodeCorrectRequest.SerializeToString,
                response_deserializer=llm__quality__pb2.CodeCorrectResponse.FromString,
                )


class LLMQualityServiceServicer(object):
    """gRPC 服务定义
    """

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AutoCorrect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMQualityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=llm__quality__pb2.GenerateRequest.FromString,
                    response_serializer=llm__quality__pb2.GenerateResponse.SerializeToString,
            ),
            'AutoCorrect': grpc.unary_unary_rpc_method_handler(
                    servicer.AutoCorrect,
                    request_deserializer=llm__quality__pb2.CodeCorrectRequest.FromString,
                    response_serializer=llm__quality__pb2.CodeCorrectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llm_quality.LLMQualityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LLMQualityService(object):
    """gRPC 服务定义
    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llm_quality.LLMQualityService/Generate',
            llm__quality__pb2.GenerateRequest.SerializeToString,
            llm__quality__pb2.GenerateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AutoCorrect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llm_quality.LLMQualityService/AutoCorrect',
            llm__quality__pb2.CodeCorrectRequest.SerializeToString,
            llm__quality__pb2.CodeCorrectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
